### PR TITLE
Update nuxt.config.js

### PR DESCRIPTION
**Pull request by vandana1499**
#1 
Changed the base URL to /docs

### CODE REVIEW

**Comment by janvig** [comment]
@vandana1499 Are you participating in [SLoP](https://slop.dscdaiict.in/)?

**Comment by vandana1499** [comment]
@janvig will you please tell me about this? I don't know about it.

**Comment by vandana1499** [comment]
Thanks for the info.

**Comment by janvig** [comment]
> @janvig will you please tell me about this? I don't know about it.

[SLoP](https://slop.dscdaiict.in/) is a program similar to GSoC, encouraging the involvement of students in open source.
Do check it out. It would help get exposure to open source software development.

**Comment by vandana1499** [comment]
Thanks @janvig

**Pull request merged**
